# yaml-language-server: $schema=https://raw.githubusercontent.com/pulumi/pulumi/master/pkg/codegen/schema/pulumi.json
---
name: catalystsquad-platform
version: 1.1.1
pluginDownloadURL: https://github.com/catalystsquad/pulumi-catalystsquad-platform/releases/download/v${VERSION}
types:
  catalystsquad-platform:index:AvailabilityZone:
    type: object
    description: >-
      Configuration supplied to AvailabilityZone list in VpcArgs to specify
      which availability zones to deploy to and what subnet configuration for
      each availability zone. Supports one private and public subnet per AZ.
    properties:
      azName:
        type: string
        description: Name of the availability zone to deploy subnets to.
      privateSubnetCidr:
        type: string
        description: >-
          CIDR for private subnets in the availability zone. If not supplied,
          the subnet is not created.
      publicSubnetCidr:
        type: string
        description: >-
          CIDR for private subnets in the availability zone. If not supplied
          the subnet is not created.
    required:
      - azName
  catalystsquad-platform:index:EksNodeGroup:
    type: object
    description: Configuration for an EKS node group
    properties:
      namePrefix:
        type: string
      desiredSize:
        type: integer
      maxSize:
        type: integer
      minSize:
        type: integer
      instanceTypes:
        type: array
        items:
          type: string
    required:
      - namePrefix
      - desiredSize
      - maxSize
      - minSize
      - instanceTypes
resources:
  catalystsquad-platform:index:Vpc:
    isComponent: true
    inputProperties:
      availabilityZoneConfig:
        type: array
        items:
          "$ref": "#/types/catalystsquad-platform:index:AvailabilityZone"
        description: >-
          Optional, list of AvailabilityZones to create subnets in. Default: []
      cidr:
        type: string
        description: >-
          Optional, CIDR block of the VPC. Default: 10.0.0.0/16
      enableEksClusterTags:
        type: boolean
        description: >-
          Optional, EKS cluster name, if VPC is used for EKS. Default: <stack
          name>
      enableEksClusterTags:
        type: boolean
        description: >-
          Optional, whether to enable required EKS cluster tags to subnets.
          Default: true
      name:
        type: string
        description: >-
          Optional, Name tag value for VPC resource. Default: <stack name>
      tags:
        type: object
        additionalProperties: 
          type: string
        description: >-
          Optional, tags to add to all resources. Default: {}
    properties:
      vpcID:
        type: string
        description: CIDR for the VPC
      publicSubnetIDs:
        type: array
        items:
          type: string
        description: IDs for all public subnets
      privateSubnetIDs:
        type: array
        items:
          type: string
        description: IDs for all private subnets
      natGatewayIPs:
        type: array
        items:
          type: string
        description: Static IPs for all NAT gateways
    required:
      - vpcID
  catalystsquad-platform:index:Eks:
    isComponent: true
    inputProperties:
      clusterName:
        type: string
        description: >-
          Optional, name of the EKS cluster. Default: <stack name>
      k8sVersion:
        type: string
        description: >-
          Optional, k8s version of the EKS cluster. Default: 1.22.6
      nodeGroupVersion:
        type: string
        description: >-
          Optional, k8s version of all node groups. Allows for upgrading the
          control plane before upgrading nodegroups. Default: <k8sVersion>
      nodeGroupConfig:
        type: array
        items:
          "$ref": "#/types/catalystsquad-platform:index:EksNodeGroup"
        description: >-
          Required, list of nodegroup configurations to create.
      enableECRAccess:
        type: boolean
        description: >-
          Optional, whether to enable ECR access policy on nodegroups. Default: true
      enableClusterAutoscalerResources:
        type: boolean
        description: >-
          Optional, whether to enable cluster autoscaler IRSA resources. Default: true
      clusterAutoscalerServiceAccount:
        type: string
        description: >-
          Optional, cluster autoscaler service account name for IRSA. Default: cluster-autoscaler
      clusterAutoscalerNamespace:
        type: string
        description: >-
          Optional, cluster autoscaler namespace for IRSA. Default: cluster-autoscaler
      enabledClusterLogTypes:
        type: string
        description: >-
          Optional, list of log types to enable on the cluster. Default: []
      subnetIDs:
        type: array
        items:
          type: string
        description: >-
          Required, list of subnet IDs to deploy the cluster and nodegroups to
    requiredInputs:
      - subnetIDs
      - nodeGroupConfig
language:
  csharp:
    # namespace override, otherwise build fails because of the `-` in catalystsquad-platform
    namespaces:
      catalystsquad-platform: CatalystsquadPlatform
    packageReferences:
      Pulumi: 3.*
      Pulumi.Aws: 5.*
  go:
    generateResourceContainerTypes: true
    importBasePath: github.com/catalystsquad/pulumi-catalystsquad-platform/sdk/go/catalystsquad-platform
  nodejs:
    dependencies:
      "@pulumi/pulumi": "^3.31.0"
      "@pulumi/aws": "^5.3.0"
    devDependencies:
      typescript: "^3.7.0"
  python:
    requires:
      pulumi: ">=3.0.0,<4.0.0"
      pulumi-aws: ">=5.0.0,<6.0.0"
