// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CatalystsquadPlatform
{
    [CatalystsquadPlatformResourceType("catalystsquad-platform:index:VeleroDependencies")]
    public partial class VeleroDependencies : Pulumi.ComponentResource
    {
        /// <summary>
        /// Create a VeleroDependencies resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public VeleroDependencies(string name, VeleroDependenciesArgs args, ComponentResourceOptions? options = null)
            : base("catalystsquad-platform:index:VeleroDependencies", name, args ?? new VeleroDependenciesArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/catalystsquad/pulumi-catalystsquad-platform/releases/download/v${VERSION}",
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class VeleroDependenciesArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Optional, whether to create the Velero S3 bucket. Allows the bucket to exist outside of pulumi. Default: true
        /// </summary>
        [Input("createBucket")]
        public Input<bool>? CreateBucket { get; set; }

        /// <summary>
        /// Required, Arn of EKS OIDC Provider for configuring the IRSA  IAM role trust relationship.
        /// </summary>
        [Input("oidcProviderArn", required: true)]
        public Input<string> OidcProviderArn { get; set; } = null!;

        /// <summary>
        /// Required, URL of EKS OIDC Provider for configuring the IRSA  IAM role trust relationship.
        /// </summary>
        [Input("oidcProviderUrl", required: true)]
        public Input<string> OidcProviderUrl { get; set; } = null!;

        /// <summary>
        /// Optional, Velero's bucket name. Default: &lt;account-id&gt;-&lt;stack-name&gt;-velero
        /// </summary>
        [Input("veleroBucketName")]
        public Input<string>? VeleroBucketName { get; set; }

        /// <summary>
        /// Optional, Velero's IAM policy name. Default: &lt;stack-name&gt;-velero-policy
        /// </summary>
        [Input("veleroIAMPolicyName")]
        public Input<string>? VeleroIAMPolicyName { get; set; }

        /// <summary>
        /// Optional, Velero's IAM role name. Default: &lt;stack-name&gt;-velero-role
        /// </summary>
        [Input("veleroIAMRoleName")]
        public Input<string>? VeleroIAMRoleName { get; set; }

        /// <summary>
        /// Optional, kubernetes namespace where Velero will exist, for configuring the IRSA IAM role trust relationship. Default: velero
        /// </summary>
        [Input("veleroNamespace")]
        public Input<string>? VeleroNamespace { get; set; }

        /// <summary>
        /// Optional, kubernetes service account name that Velero will use, for configuring the IRSA IAM role trust relationship. Default: velero
        /// </summary>
        [Input("veleroServiceAccount")]
        public Input<string>? VeleroServiceAccount { get; set; }

        public VeleroDependenciesArgs()
        {
        }
    }
}
