# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .argocd_app import *
from .cluster_bootstrap import *
from .eks import *
from .observability_dependencies import *
from .provider import *
from .vpc import *
from ._inputs import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "catalystsquad-platform",
  "mod": "index",
  "fqn": "pulumi_catalystsquad_platform",
  "classes": {
   "catalystsquad-platform:index:ArgocdApp": "ArgocdApp",
   "catalystsquad-platform:index:ClusterBootstrap": "ClusterBootstrap",
   "catalystsquad-platform:index:Eks": "Eks",
   "catalystsquad-platform:index:ObservabilityDependencies": "ObservabilityDependencies",
   "catalystsquad-platform:index:Vpc": "Vpc"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "catalystsquad-platform",
  "token": "pulumi:providers:catalystsquad-platform",
  "fqn": "pulumi_catalystsquad_platform",
  "class": "Provider"
 }
]
"""
)
