# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = ['ObservabilityDependenciesArgs', 'ObservabilityDependencies']

@pulumi.input_type
class ObservabilityDependenciesArgs:
    def __init__(__self__, *,
                 oidc_provider_arn: pulumi.Input[str],
                 oidc_provider_url: pulumi.Input[str],
                 loki_iam_policy_name: Optional[pulumi.Input[str]] = None,
                 cortex_bucket_name: Optional[pulumi.Input[str]] = None,
                 cortex_iam_policy_name: Optional[pulumi.Input[str]] = None,
                 cortex_iam_role_name: Optional[pulumi.Input[str]] = None,
                 cortex_namespace: Optional[pulumi.Input[str]] = None,
                 cortex_service_account: Optional[pulumi.Input[str]] = None,
                 loki_bucket_name: Optional[pulumi.Input[str]] = None,
                 loki_iam_role_name: Optional[pulumi.Input[str]] = None,
                 loki_namespace: Optional[pulumi.Input[str]] = None,
                 loki_service_account: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a ObservabilityDependencies resource.
        :param pulumi.Input[str] oidc_provider_arn: Required, Arn of EKS OIDC Provider for configuring the IRSA  IAM role trust relationship.
        :param pulumi.Input[str] oidc_provider_url: Required, URL of EKS OIDC Provider for configuring the IRSA  IAM role trust relationship.
        :param pulumi.Input[str] loki_iam_policy_name: Optional, Loki's IAM policy name. Default: loki-policy
        :param pulumi.Input[str] cortex_bucket_name: Optional, name of bucket to create for Cortex. Default: <account-id>-<stack-name>-cortex
        :param pulumi.Input[str] cortex_iam_policy_name: Optional, Cortex's IAM policy name. Default: cortex-policy
        :param pulumi.Input[str] cortex_iam_role_name: Optional, Cortex's IAM role name. Default: cortex-role
        :param pulumi.Input[str] cortex_namespace: Optional, kubernetes namespace where Cortex will exist, for configuring the IRSA IAM role trust relationship. Default: cortex
        :param pulumi.Input[str] cortex_service_account: Optional, kubernetes service account name that Cortex will use, for configuring the IRSA IAM role trust relationship. Default: cortex
        :param pulumi.Input[str] loki_bucket_name: Optional, name of bucket to create for Loki. Default: <account-id>-<stack-name>-loki
        :param pulumi.Input[str] loki_iam_role_name: Optional, Loki's IAM role name. Default: loki-role
        :param pulumi.Input[str] loki_namespace: Optional, kubernetes namespace where Loki will exist, for configuring the IRSA IAM role trust relationship. Default: loki
        :param pulumi.Input[str] loki_service_account: Optional, kubernetes service account name that Loki will use, for configuring the IRSA IAM role trust relationship. Default: loki
        """
        pulumi.set(__self__, "oidc_provider_arn", oidc_provider_arn)
        pulumi.set(__self__, "oidc_provider_url", oidc_provider_url)
        if loki_iam_policy_name is not None:
            pulumi.set(__self__, "loki_iam_policy_name", loki_iam_policy_name)
        if cortex_bucket_name is not None:
            pulumi.set(__self__, "cortex_bucket_name", cortex_bucket_name)
        if cortex_iam_policy_name is not None:
            pulumi.set(__self__, "cortex_iam_policy_name", cortex_iam_policy_name)
        if cortex_iam_role_name is not None:
            pulumi.set(__self__, "cortex_iam_role_name", cortex_iam_role_name)
        if cortex_namespace is not None:
            pulumi.set(__self__, "cortex_namespace", cortex_namespace)
        if cortex_service_account is not None:
            pulumi.set(__self__, "cortex_service_account", cortex_service_account)
        if loki_bucket_name is not None:
            pulumi.set(__self__, "loki_bucket_name", loki_bucket_name)
        if loki_iam_role_name is not None:
            pulumi.set(__self__, "loki_iam_role_name", loki_iam_role_name)
        if loki_namespace is not None:
            pulumi.set(__self__, "loki_namespace", loki_namespace)
        if loki_service_account is not None:
            pulumi.set(__self__, "loki_service_account", loki_service_account)

    @property
    @pulumi.getter(name="oidcProviderArn")
    def oidc_provider_arn(self) -> pulumi.Input[str]:
        """
        Required, Arn of EKS OIDC Provider for configuring the IRSA  IAM role trust relationship.
        """
        return pulumi.get(self, "oidc_provider_arn")

    @oidc_provider_arn.setter
    def oidc_provider_arn(self, value: pulumi.Input[str]):
        pulumi.set(self, "oidc_provider_arn", value)

    @property
    @pulumi.getter(name="oidcProviderUrl")
    def oidc_provider_url(self) -> pulumi.Input[str]:
        """
        Required, URL of EKS OIDC Provider for configuring the IRSA  IAM role trust relationship.
        """
        return pulumi.get(self, "oidc_provider_url")

    @oidc_provider_url.setter
    def oidc_provider_url(self, value: pulumi.Input[str]):
        pulumi.set(self, "oidc_provider_url", value)

    @property
    @pulumi.getter(name="LokiIAMPolicyName")
    def loki_iam_policy_name(self) -> Optional[pulumi.Input[str]]:
        """
        Optional, Loki's IAM policy name. Default: loki-policy
        """
        return pulumi.get(self, "loki_iam_policy_name")

    @loki_iam_policy_name.setter
    def loki_iam_policy_name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "loki_iam_policy_name", value)

    @property
    @pulumi.getter(name="cortexBucketName")
    def cortex_bucket_name(self) -> Optional[pulumi.Input[str]]:
        """
        Optional, name of bucket to create for Cortex. Default: <account-id>-<stack-name>-cortex
        """
        return pulumi.get(self, "cortex_bucket_name")

    @cortex_bucket_name.setter
    def cortex_bucket_name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "cortex_bucket_name", value)

    @property
    @pulumi.getter(name="cortexIAMPolicyName")
    def cortex_iam_policy_name(self) -> Optional[pulumi.Input[str]]:
        """
        Optional, Cortex's IAM policy name. Default: cortex-policy
        """
        return pulumi.get(self, "cortex_iam_policy_name")

    @cortex_iam_policy_name.setter
    def cortex_iam_policy_name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "cortex_iam_policy_name", value)

    @property
    @pulumi.getter(name="cortexIAMRoleName")
    def cortex_iam_role_name(self) -> Optional[pulumi.Input[str]]:
        """
        Optional, Cortex's IAM role name. Default: cortex-role
        """
        return pulumi.get(self, "cortex_iam_role_name")

    @cortex_iam_role_name.setter
    def cortex_iam_role_name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "cortex_iam_role_name", value)

    @property
    @pulumi.getter(name="cortexNamespace")
    def cortex_namespace(self) -> Optional[pulumi.Input[str]]:
        """
        Optional, kubernetes namespace where Cortex will exist, for configuring the IRSA IAM role trust relationship. Default: cortex
        """
        return pulumi.get(self, "cortex_namespace")

    @cortex_namespace.setter
    def cortex_namespace(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "cortex_namespace", value)

    @property
    @pulumi.getter(name="cortexServiceAccount")
    def cortex_service_account(self) -> Optional[pulumi.Input[str]]:
        """
        Optional, kubernetes service account name that Cortex will use, for configuring the IRSA IAM role trust relationship. Default: cortex
        """
        return pulumi.get(self, "cortex_service_account")

    @cortex_service_account.setter
    def cortex_service_account(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "cortex_service_account", value)

    @property
    @pulumi.getter(name="lokiBucketName")
    def loki_bucket_name(self) -> Optional[pulumi.Input[str]]:
        """
        Optional, name of bucket to create for Loki. Default: <account-id>-<stack-name>-loki
        """
        return pulumi.get(self, "loki_bucket_name")

    @loki_bucket_name.setter
    def loki_bucket_name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "loki_bucket_name", value)

    @property
    @pulumi.getter(name="lokiIAMRoleName")
    def loki_iam_role_name(self) -> Optional[pulumi.Input[str]]:
        """
        Optional, Loki's IAM role name. Default: loki-role
        """
        return pulumi.get(self, "loki_iam_role_name")

    @loki_iam_role_name.setter
    def loki_iam_role_name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "loki_iam_role_name", value)

    @property
    @pulumi.getter(name="lokiNamespace")
    def loki_namespace(self) -> Optional[pulumi.Input[str]]:
        """
        Optional, kubernetes namespace where Loki will exist, for configuring the IRSA IAM role trust relationship. Default: loki
        """
        return pulumi.get(self, "loki_namespace")

    @loki_namespace.setter
    def loki_namespace(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "loki_namespace", value)

    @property
    @pulumi.getter(name="lokiServiceAccount")
    def loki_service_account(self) -> Optional[pulumi.Input[str]]:
        """
        Optional, kubernetes service account name that Loki will use, for configuring the IRSA IAM role trust relationship. Default: loki
        """
        return pulumi.get(self, "loki_service_account")

    @loki_service_account.setter
    def loki_service_account(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "loki_service_account", value)


class ObservabilityDependencies(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 loki_iam_policy_name: Optional[pulumi.Input[str]] = None,
                 cortex_bucket_name: Optional[pulumi.Input[str]] = None,
                 cortex_iam_policy_name: Optional[pulumi.Input[str]] = None,
                 cortex_iam_role_name: Optional[pulumi.Input[str]] = None,
                 cortex_namespace: Optional[pulumi.Input[str]] = None,
                 cortex_service_account: Optional[pulumi.Input[str]] = None,
                 loki_bucket_name: Optional[pulumi.Input[str]] = None,
                 loki_iam_role_name: Optional[pulumi.Input[str]] = None,
                 loki_namespace: Optional[pulumi.Input[str]] = None,
                 loki_service_account: Optional[pulumi.Input[str]] = None,
                 oidc_provider_arn: Optional[pulumi.Input[str]] = None,
                 oidc_provider_url: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Create a ObservabilityDependencies resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] loki_iam_policy_name: Optional, Loki's IAM policy name. Default: loki-policy
        :param pulumi.Input[str] cortex_bucket_name: Optional, name of bucket to create for Cortex. Default: <account-id>-<stack-name>-cortex
        :param pulumi.Input[str] cortex_iam_policy_name: Optional, Cortex's IAM policy name. Default: cortex-policy
        :param pulumi.Input[str] cortex_iam_role_name: Optional, Cortex's IAM role name. Default: cortex-role
        :param pulumi.Input[str] cortex_namespace: Optional, kubernetes namespace where Cortex will exist, for configuring the IRSA IAM role trust relationship. Default: cortex
        :param pulumi.Input[str] cortex_service_account: Optional, kubernetes service account name that Cortex will use, for configuring the IRSA IAM role trust relationship. Default: cortex
        :param pulumi.Input[str] loki_bucket_name: Optional, name of bucket to create for Loki. Default: <account-id>-<stack-name>-loki
        :param pulumi.Input[str] loki_iam_role_name: Optional, Loki's IAM role name. Default: loki-role
        :param pulumi.Input[str] loki_namespace: Optional, kubernetes namespace where Loki will exist, for configuring the IRSA IAM role trust relationship. Default: loki
        :param pulumi.Input[str] loki_service_account: Optional, kubernetes service account name that Loki will use, for configuring the IRSA IAM role trust relationship. Default: loki
        :param pulumi.Input[str] oidc_provider_arn: Required, Arn of EKS OIDC Provider for configuring the IRSA  IAM role trust relationship.
        :param pulumi.Input[str] oidc_provider_url: Required, URL of EKS OIDC Provider for configuring the IRSA  IAM role trust relationship.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ObservabilityDependenciesArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a ObservabilityDependencies resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param ObservabilityDependenciesArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ObservabilityDependenciesArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 loki_iam_policy_name: Optional[pulumi.Input[str]] = None,
                 cortex_bucket_name: Optional[pulumi.Input[str]] = None,
                 cortex_iam_policy_name: Optional[pulumi.Input[str]] = None,
                 cortex_iam_role_name: Optional[pulumi.Input[str]] = None,
                 cortex_namespace: Optional[pulumi.Input[str]] = None,
                 cortex_service_account: Optional[pulumi.Input[str]] = None,
                 loki_bucket_name: Optional[pulumi.Input[str]] = None,
                 loki_iam_role_name: Optional[pulumi.Input[str]] = None,
                 loki_namespace: Optional[pulumi.Input[str]] = None,
                 loki_service_account: Optional[pulumi.Input[str]] = None,
                 oidc_provider_arn: Optional[pulumi.Input[str]] = None,
                 oidc_provider_url: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        if opts is None:
            opts = pulumi.ResourceOptions()
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.version is None:
            opts.version = _utilities.get_version()
        if opts.plugin_download_url is None:
            opts.plugin_download_url = _utilities.get_plugin_download_url()
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ObservabilityDependenciesArgs.__new__(ObservabilityDependenciesArgs)

            __props__.__dict__["loki_iam_policy_name"] = loki_iam_policy_name
            __props__.__dict__["cortex_bucket_name"] = cortex_bucket_name
            __props__.__dict__["cortex_iam_policy_name"] = cortex_iam_policy_name
            __props__.__dict__["cortex_iam_role_name"] = cortex_iam_role_name
            __props__.__dict__["cortex_namespace"] = cortex_namespace
            __props__.__dict__["cortex_service_account"] = cortex_service_account
            __props__.__dict__["loki_bucket_name"] = loki_bucket_name
            __props__.__dict__["loki_iam_role_name"] = loki_iam_role_name
            __props__.__dict__["loki_namespace"] = loki_namespace
            __props__.__dict__["loki_service_account"] = loki_service_account
            if oidc_provider_arn is None and not opts.urn:
                raise TypeError("Missing required property 'oidc_provider_arn'")
            __props__.__dict__["oidc_provider_arn"] = oidc_provider_arn
            if oidc_provider_url is None and not opts.urn:
                raise TypeError("Missing required property 'oidc_provider_url'")
            __props__.__dict__["oidc_provider_url"] = oidc_provider_url
        super(ObservabilityDependencies, __self__).__init__(
            'catalystsquad-platform:index:ObservabilityDependencies',
            resource_name,
            __props__,
            opts,
            remote=True)

