// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CatalystsquadPlatform.Inputs
{

    public sealed class ArgocdApplicationSpecSourceArgs : Pulumi.ResourceArgs
    {
        [Input("chart")]
        public Input<string>? Chart { get; set; }

        [Input("directory")]
        public Input<Inputs.DirectorySourceArgs>? Directory { get; set; }

        [Input("helm")]
        public Input<Inputs.HelmSourceArgs>? Helm { get; set; }

        [Input("kustomize")]
        public Input<Inputs.KustomizeSourceArgs>? Kustomize { get; set; }

        [Input("path")]
        public Input<string>? Path { get; set; }

        [Input("plugin")]
        public Input<Inputs.PluginSourceArgs>? Plugin { get; set; }

        [Input("repoURL")]
        public Input<string>? RepoURL { get; set; }

        [Input("targetRevision")]
        public Input<string>? TargetRevision { get; set; }

        public ArgocdApplicationSpecSourceArgs()
        {
        }
    }
}
