// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CatalystsquadPlatform.Inputs
{

    public sealed class ArgocdApplicationSyncPolicyArgs : Pulumi.ResourceArgs
    {
        [Input("automated")]
        public Input<Inputs.SyncPolicyAutomatedArgs>? Automated { get; set; }

        [Input("retry")]
        public Input<Inputs.SyncPolicyRetryArgs>? Retry { get; set; }

        [Input("syncOptions")]
        private InputList<string>? _syncOptions;
        public InputList<string> SyncOptions
        {
            get => _syncOptions ?? (_syncOptions = new InputList<string>());
            set => _syncOptions = value;
        }

        public ArgocdApplicationSyncPolicyArgs()
        {
        }
    }
}
