// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CatalystsquadPlatform.Inputs
{

    public sealed class ArgocdApplicationSpecArgs : Pulumi.ResourceArgs
    {
        [Input("destination")]
        public Input<Inputs.ArgocdApplicationSpecDestinationArgs>? Destination { get; set; }

        [Input("ignoreDifferences")]
        private InputList<Inputs.ArgocdApplicationIgnoreDifferencesArgs>? _ignoreDifferences;
        public InputList<Inputs.ArgocdApplicationIgnoreDifferencesArgs> IgnoreDifferences
        {
            get => _ignoreDifferences ?? (_ignoreDifferences = new InputList<Inputs.ArgocdApplicationIgnoreDifferencesArgs>());
            set => _ignoreDifferences = value;
        }

        [Input("project")]
        public Input<string>? Project { get; set; }

        [Input("source")]
        public Input<Inputs.ArgocdApplicationSpecSourceArgs>? Source { get; set; }

        [Input("syncPolicy")]
        public Input<Inputs.ArgocdApplicationSyncPolicyArgs>? SyncPolicy { get; set; }

        public ArgocdApplicationSpecArgs()
        {
        }
    }
}
