// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CatalystsquadPlatform.Inputs
{

    public sealed class ArgocdApplicationIgnoreDifferencesArgs : Pulumi.ResourceArgs
    {
        [Input("group")]
        public Input<string>? Group { get; set; }

        [Input("jqPathExpressions")]
        private InputList<string>? _jqPathExpressions;
        public InputList<string> JqPathExpressions
        {
            get => _jqPathExpressions ?? (_jqPathExpressions = new InputList<string>());
            set => _jqPathExpressions = value;
        }

        [Input("jsonPointers")]
        private InputList<string>? _jsonPointers;
        public InputList<string> JsonPointers
        {
            get => _jsonPointers ?? (_jsonPointers = new InputList<string>());
            set => _jsonPointers = value;
        }

        [Input("kind")]
        public Input<string>? Kind { get; set; }

        [Input("managedFieldsManagers")]
        private InputList<string>? _managedFieldsManagers;
        public InputList<string> ManagedFieldsManagers
        {
            get => _managedFieldsManagers ?? (_managedFieldsManagers = new InputList<string>());
            set => _managedFieldsManagers = value;
        }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        public ArgocdApplicationIgnoreDifferencesArgs()
        {
        }
    }
}
