// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CatalystsquadPlatform.Inputs
{

    /// <summary>
    /// Configuration for the EKS auth configmap
    /// </summary>
    public sealed class AuthConfigMapConfigArgs : Pulumi.ResourceArgs
    {
        [Input("autoDiscoverSSORoles")]
        private InputList<Inputs.SSORolePermissionSetConfigArgs>? _autoDiscoverSSORoles;

        /// <summary>
        /// Optional, list of AWS SSO permission set roles to autodiscover.
        /// </summary>
        public InputList<Inputs.SSORolePermissionSetConfigArgs> AutoDiscoverSSORoles
        {
            get => _autoDiscoverSSORoles ?? (_autoDiscoverSSORoles = new InputList<Inputs.SSORolePermissionSetConfigArgs>());
            set => _autoDiscoverSSORoles = value;
        }

        [Input("iamRoles")]
        private InputList<Inputs.IAMIdentityConfigArgs>? _iamRoles;

        /// <summary>
        /// Optional, list of IAM roles to grant access in the auth configmap
        /// </summary>
        public InputList<Inputs.IAMIdentityConfigArgs> IamRoles
        {
            get => _iamRoles ?? (_iamRoles = new InputList<Inputs.IAMIdentityConfigArgs>());
            set => _iamRoles = value;
        }

        [Input("iamUsers")]
        private InputList<Inputs.IAMIdentityConfigArgs>? _iamUsers;

        /// <summary>
        /// Optional, list of IAM users to grant access in the auth configmap
        /// </summary>
        public InputList<Inputs.IAMIdentityConfigArgs> IamUsers
        {
            get => _iamUsers ?? (_iamUsers = new InputList<Inputs.IAMIdentityConfigArgs>());
            set => _iamUsers = value;
        }

        public AuthConfigMapConfigArgs()
        {
        }
    }
}
