// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CatalystsquadPlatform.Inputs
{

    public sealed class DirectorySourceJsonnetArgs : Pulumi.ResourceArgs
    {
        [Input("TLAs")]
        private InputList<Inputs.JsonnetVarArgs>? _TLAs;
        public InputList<Inputs.JsonnetVarArgs> TLAs
        {
            get => _TLAs ?? (_TLAs = new InputList<Inputs.JsonnetVarArgs>());
            set => _TLAs = value;
        }

        [Input("extVars")]
        private InputList<Inputs.JsonnetVarArgs>? _extVars;
        public InputList<Inputs.JsonnetVarArgs> ExtVars
        {
            get => _extVars ?? (_extVars = new InputList<Inputs.JsonnetVarArgs>());
            set => _extVars = value;
        }

        [Input("libs")]
        private InputList<string>? _libs;
        public InputList<string> Libs
        {
            get => _libs ?? (_libs = new InputList<string>());
            set => _libs = value;
        }

        public DirectorySourceJsonnetArgs()
        {
        }
    }
}
