// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CatalystsquadPlatform.Inputs
{

    /// <summary>
    /// Configuration for an EKS node group
    /// </summary>
    public sealed class EksNodeGroupArgs : Pulumi.ResourceArgs
    {
        [Input("desiredSize", required: true)]
        public Input<int> DesiredSize { get; set; } = null!;

        [Input("instanceTypes", required: true)]
        private InputList<string>? _instanceTypes;
        public InputList<string> InstanceTypes
        {
            get => _instanceTypes ?? (_instanceTypes = new InputList<string>());
            set => _instanceTypes = value;
        }

        [Input("maxSize", required: true)]
        public Input<int> MaxSize { get; set; } = null!;

        [Input("minSize", required: true)]
        public Input<int> MinSize { get; set; } = null!;

        [Input("namePrefix", required: true)]
        public Input<string> NamePrefix { get; set; } = null!;

        public EksNodeGroupArgs()
        {
        }
    }
}
