// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CatalystsquadPlatform.Inputs
{

    /// <summary>
    /// Configuration for a helm release
    /// </summary>
    public sealed class HelmReleaseConfigArgs : Pulumi.ResourceArgs
    {
        [Input("values")]
        private InputMap<string>? _values;

        /// <summary>
        /// Optional for each implementation, empty by default
        /// </summary>
        public InputMap<string> Values
        {
            get => _values ?? (_values = new InputMap<string>());
            set => _values = value;
        }

        [Input("valuesFiles")]
        private InputList<string>? _valuesFiles;

        /// <summary>
        /// Optional for each implementation, empty by default
        /// </summary>
        public InputList<string> ValuesFiles
        {
            get => _valuesFiles ?? (_valuesFiles = new InputList<string>());
            set => _valuesFiles = value;
        }

        /// <summary>
        /// Optional for each implementation, defaults specific to each helm chart
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public HelmReleaseConfigArgs()
        {
        }
    }
}
