// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CatalystsquadPlatform.Inputs
{

    public sealed class IAMIdentityConfigArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Required, ARN of IAM role to use in configmap
        /// </summary>
        [Input("arn")]
        public Input<string>? Arn { get; set; }

        [Input("permissionGroups")]
        private InputList<string>? _permissionGroups;

        /// <summary>
        /// Required, permission groups to add role to. Ex: system:masters
        /// </summary>
        public InputList<string> PermissionGroups
        {
            get => _permissionGroups ?? (_permissionGroups = new InputList<string>());
            set => _permissionGroups = value;
        }

        /// <summary>
        /// Optional username field, defaults to role name
        /// </summary>
        [Input("username")]
        public Input<string>? Username { get; set; }

        public IAMIdentityConfigArgs()
        {
        }
    }
}
