// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CatalystsquadPlatform.Inputs
{

    /// <summary>
    /// Configuration for platform application
    /// </summary>
    public sealed class PlatformApplicationConfigArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Optional, value of certmanager dns resolver secret
        /// </summary>
        [Input("certManagerDnsSolverSecret")]
        public Input<string>? CertManagerDnsSolverSecret { get; set; }

        /// <summary>
        /// Optional, sync policy of platform application config.
        /// </summary>
        [Input("syncPolicy")]
        public Input<Inputs.ArgocdApplicationSyncPolicyArgs>? SyncPolicy { get; set; }

        /// <summary>
        /// Optional, target revision of platform application config. Deafult: &gt;=1.0.0-alpha
        /// </summary>
        [Input("targetRevision")]
        public Input<string>? TargetRevision { get; set; }

        /// <summary>
        /// Optional, platform application values
        /// </summary>
        [Input("values")]
        public Input<string>? Values { get; set; }

        public PlatformApplicationConfigArgs()
        {
        }
    }
}
