// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CatalystsquadPlatform.Inputs
{

    public sealed class PluginSourceArgs : Pulumi.ResourceArgs
    {
        [Input("env")]
        private InputList<Inputs.PluginSourceEnvArgs>? _env;
        public InputList<Inputs.PluginSourceEnvArgs> Env
        {
            get => _env ?? (_env = new InputList<Inputs.PluginSourceEnvArgs>());
            set => _env = value;
        }

        [Input("name")]
        public Input<string>? Name { get; set; }

        public PluginSourceArgs()
        {
        }
    }
}
