// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CatalystsquadPlatform.Inputs
{

    /// <summary>
    /// Configuration for a Prometheus remoteWrite config secret.
    /// </summary>
    public sealed class PrometheusRemoteWriteConfigArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Required, basic auth password.
        /// </summary>
        [Input("basicAuthPassword")]
        public Input<string>? BasicAuthPassword { get; set; }

        /// <summary>
        /// Optional, basic auth username. Default: &lt;stack name&gt;
        /// </summary>
        [Input("basicAuthUsername")]
        public Input<string>? BasicAuthUsername { get; set; }

        /// <summary>
        /// Optional, basic auth secret name. Default: prometheus-remote-write-basic-auth
        /// </summary>
        [Input("secretName")]
        public Input<string>? SecretName { get; set; }

        public PrometheusRemoteWriteConfigArgs()
        {
        }
    }
}
