// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CatalystsquadPlatform.Inputs
{

    public sealed class RetryBackoffArgs : Pulumi.ResourceArgs
    {
        [Input("duration")]
        public Input<string>? Duration { get; set; }

        [Input("factor")]
        public Input<int>? Factor { get; set; }

        [Input("maxDuration")]
        public Input<string>? MaxDuration { get; set; }

        public RetryBackoffArgs()
        {
        }
    }
}
