// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CatalystsquadPlatform.Inputs
{

    public sealed class SyncPolicyAutomatedArgs : Pulumi.ResourceArgs
    {
        [Input("allowEmpty")]
        public Input<bool>? AllowEmpty { get; set; }

        [Input("prune")]
        public Input<bool>? Prune { get; set; }

        [Input("selfHeal")]
        public Input<bool>? SelfHeal { get; set; }

        public SyncPolicyAutomatedArgs()
        {
        }
    }
}
