// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export class Vpc extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'catalystsquad-platform:index:Vpc';

    /**
     * Returns true if the given object is an instance of Vpc.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Vpc {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Vpc.__pulumiType;
    }

    /**
     * Static IPs for all NAT gateways
     */
    public /*out*/ readonly natGatewayIPs!: pulumi.Output<string[] | undefined>;
    /**
     * IDs for all private subnets
     */
    public /*out*/ readonly privateSubnetIDs!: pulumi.Output<string[] | undefined>;
    /**
     * IDs for all public subnets
     */
    public /*out*/ readonly publicSubnetIDs!: pulumi.Output<string[] | undefined>;
    /**
     * CIDR for the VPC
     */
    public /*out*/ readonly vpcID!: pulumi.Output<string>;

    /**
     * Create a Vpc resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: VpcArgs, opts?: pulumi.ComponentResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            inputs["availabilityZoneConfig"] = args ? args.availabilityZoneConfig : undefined;
            inputs["cidr"] = args ? args.cidr : undefined;
            inputs["enableEksClusterTags"] = args ? args.enableEksClusterTags : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["tags"] = args ? args.tags : undefined;
            inputs["natGatewayIPs"] = undefined /*out*/;
            inputs["privateSubnetIDs"] = undefined /*out*/;
            inputs["publicSubnetIDs"] = undefined /*out*/;
            inputs["vpcID"] = undefined /*out*/;
        } else {
            inputs["natGatewayIPs"] = undefined /*out*/;
            inputs["privateSubnetIDs"] = undefined /*out*/;
            inputs["publicSubnetIDs"] = undefined /*out*/;
            inputs["vpcID"] = undefined /*out*/;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(Vpc.__pulumiType, name, inputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a Vpc resource.
 */
export interface VpcArgs {
    /**
     * Optional, list of AvailabilityZones to create subnets in. Default: []
     */
    readonly availabilityZoneConfig?: pulumi.Input<pulumi.Input<inputs.AvailabilityZoneArgs>[]>;
    /**
     * Optional, CIDR block of the VPC. Default: 10.0.0.0/16
     */
    readonly cidr?: pulumi.Input<string>;
    /**
     * Optional, whether to enable required EKS cluster tags to subnets. Default: true
     */
    readonly enableEksClusterTags?: pulumi.Input<boolean>;
    /**
     * Optional, Name tag value for VPC resource. Default: <stack name>
     */
    readonly name?: pulumi.Input<string>;
    /**
     * Optional, tags to add to all resources. Default: {}
     */
    readonly tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}
